#!/usr/bin/env bash
# workflow-2.sh — 刑事辩护流程 (从侦查到审判) SOP walkthrough for 中国法律执业.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中国法律执业"
WORKFLOW="刑事辩护流程 (从侦查到审判)"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "刑事辩护流程 (从侦查到审判)" 工作流。

一句话: 从委托人接受刑事侦查 / 拘留 / 逮捕到法院判决的全流程辩护标准动作

入门 SOP 共 6 步, 失败模式自检 12 项。

相关心智模型:
  • 程序先于实体 — 时效 / 管辖 / 主体 错一个就输: 实体法 (民法典 / 刑法 / 公司法) 决定「谁对谁错」, 程序法 (民诉 / 刑诉 / 行诉) 决定「能不能进法院」. 程序错了, 实体上多对都没用.
  • 法律不是结论, 是程序 + 论证 — 「依法」≠「我说的就对」: 法律给的不是「答案」, 是「论证路径 + 证据规则 + 程序」. 同一事实下不同律师 / 不同法官可能得出不同结果, 这不是错, 是法律的本质.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**接受委托** — 家属 / 嫌疑人本人委托 (家属优先, 因嫌疑人在押) + 委托手续 + 律师执业证 + 律所介绍信"
  "**会见嫌疑人** —"
  "**侦查阶段策略** —"
  "**审查起诉阶段** —"
  "**审判阶段** —"
  "**二审 + 申诉** — 一审不利时, 上诉 + 申诉 + 必要时再审"
)
declare -a FAILURE_MODES=(
  "**会见迟 / 走过场** → 嫌疑人不知权利 / 错过黄金期"
  "**不阅卷直接辩护** → 不知公诉证据 = 抓瞎"
  "**罪名先入为主** → 错过更轻罪名辩护 (如盗窃 vs 诈骗 / 贪污 vs 受贿)"
  "**认罪认罚乱劝** → 不该认的认了 → 量刑虽减, 但失去辩护空间"
  "**家属期望失控** → 「无罪」期望 vs 「缓刑」结果, 客户灾难"
  "**程序违法漏揭** → 刑讯逼供 / 超期羁押 不主张 → 错过证据排除"
  "**不研究类案** → 同罪名量刑差距大, 不知道争取空间"
  "**二审上诉决定迟** → 上诉期 10 日 (一审判决送达起算), 不能错过"
  "**关键决策点**:"
  "取保候审申请: 案情 / 嫌疑人情况 (病 / 怀孕 / 老 / 未成年) / 罪名严重度"
  "认罪认罚: 证据是否确凿 + 罪名是否准确 + 量刑空间 + 嫌疑人意愿"
  "上诉 / 申诉: 一审判决错误 + 新证据 + 程序违法 + 法律适用错误"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
