#!/usr/bin/env bash
# workflow-1.sh — 商单笔记生产 (蒲公英报备流程) SOP walkthrough for 小红书运营.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="小红书运营"
WORKFLOW="商单笔记生产 (蒲公英报备流程)"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "商单笔记生产 (蒲公英报备流程)" 工作流。

一句话: 接到品牌商单后, 从 brief 到爆款内容的标准产出流程 — 报备 + 内容 + 数据三件套.

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 内容是种草, 不是销售 (核心 PASS): 小红书的内容逻辑是「让用户自己想买」, 不是「告诉用户来买」. 硬广直发必死.
  • 数据反馈驱动迭代 (核心 PASS): 小红书运营是**测试驱动的**, 不是经验驱动的 — 每篇笔记都是 A/B 测试.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**拆品牌 brief** (Day 1): 必填卖点 / 禁忌词 / 投放预期. 不要全盘照搬, 提炼出 1-2 个真正能种草的点."
  "**选题反推** (Day 1-2): 用户痛点角度切入, 不是品牌角度. 用千瓜 / 新红 看竞品同类商单选题, 选差异化角度."
  "**内容创作** (Day 2-4): 真实场景 + 软植入 + 真人感. 品牌信息植入比例 ≤ 30% (软植入是 5-10%). 至少 80% 内容是真实使用 / 体验 / 测评."
  "**蒲公英平台报备** (Day 4): 商单笔记必须报. 报备后才能合规接单. 商单笔记会带「赞助」标识 (但不影响算法)."
  "**发布后 24 小时跟数据** (Day 5): 看互动率 / 收藏率 / 完读率. 数据达品牌 KPI 80% 以上算合格."
  "**决定是否投流加热** (Day 5-7): 自然流好但还没到 KPI → 上薯条加热. 自然流差 → 不要硬投流, 节省预算."
)
declare -a FAILURE_MODES=(
  "品牌信息过密 → 用户跳出 → 数据死"
  "不报备 → 平台一查就限流, 商单也黄了"
  "选题从品牌卖点出发 → 没人愿意看"
  "一次接 ≥ 5 条同品类商单 → 蒲公英信用等级降级 (Lv2 → Lv1)"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
