#!/usr/bin/env bash
# workflow-1.sh — 急性踝扭伤评估 + 保守治疗启动 SOP walkthrough for 足踝外科.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="足踝外科"
WORKFLOW="急性踝扭伤评估 + 保守治疗启动"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "急性踝扭伤评估 + 保守治疗启动" 工作流。

一句话: 从急诊 / 门诊接到急性踝扭伤患者, 到完成评估 + 启动保守治疗的标准动作 (24-72 小时窗口)

入门 SOP 共 8 步, 失败模式自检 11 项。

相关心智模型:
  • 保守治疗优先于手术 (3-6 月黄金期): 90% 的足踝慢性病变不需要手术, 但很多医生 / 患者直接跳到手术决策, 跳过保守治疗黄金期.
  • 影像学发现 ≠ 临床症状原因 (跟着症状走): MRI 看到的「异常」很多跟患者主诉无关. 影像跟症状对不上时, 跟着症状走, 不是跟着影像走.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**病史采集** — 受伤机制 (内翻 / 外翻 / 旋转 / 高位扭伤?) + 当时是否听到 \"pop\" 声 + 当下能否承重 + 既往扭伤史 + 患者活动需求 (运动员? 老年? 高龄独居?)"
  "**体格检查** — 肿胀范围 (踝外侧 vs 内侧 vs 高位) + 压痛点 (ATFL 远端 / CFL / 三角韧带 / 5th 跖骨基底 / 腓骨远端) + 抽屉试验 + 内翻应力试验 + Squeeze 试验 (高位踝扭伤排查)"
  "**Ottawa Ankle Rules 判断**:"
  "**必要时 MRI** — 高位踝扭伤怀疑 syndesmosis 损伤 / 临床体征怀疑韧带完全断裂 / 6 周以上无改善"
  "**严重度分级**:"
  "**启动 PRICE+ 方案**:"
  "**启动康复** — 急性期过后 (3-7 天) 开始 ROM + 渐进负重 + 平衡训练 + 力量训练. 推荐 PT 介入"
  "**复诊计划** — 1 周 / 4 周 / 12 周, 每次评估恢复度 + 是否需调整"
)
declare -a FAILURE_MODES=(
  "**不分级一律石膏** → 韧带挛缩, 慢性踝关节不稳率 30%+"
  "**跳过 Ottawa rules 直接 X 线** → 浪费医保 + 辐射"
  "**不给康复方案** → 二次扭伤率 30%+"
  "**漏诊高位踝扭伤** → 慢性踝痛 + syndesmosis 不稳"
  "**漏诊 Lisfranc 损伤** → 中足关节炎远期后果"
  "**运动员太早回归** → 二次扭伤 / 慢性不稳 / 中年关节炎"
  "**患者教育模糊「多休息 + 少走」** → 患者不知道怎么做, 依从性差"
  "**关键决策点**:"
  "何时手术: Grade III 完全断裂 + 年轻 / 运动员 → 手术评估; 普通人 / Grade II 以下 → 一律保守"
  "何时进 PT: 急性期过后 (3-7 天) 立即, 不要等 6 周"
  "何时怀疑慢性踝不稳: 复发性扭伤 ≥ 3 次或 6 个月以上仍主观「打软腿」"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
